// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pomshupfbpdjctwkxuwn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvbXNodXBmYnBkamN0d2t4dXduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MDgzMTcsImV4cCI6MjA3NDQ4NDMxN30.FjR4XYtp5_lVaJ6VZKOyNn5bLhFT_y8ekCR3GoZURlc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});